### ISSUE TITLE
caminfoのattribute error

### ISSUE THREAD

**Issue by ASAKA-219** [GAI-313/tello_driver_for_noetic#1]
`roslaunch tello_driver tello_node.launch 
`
したところ、以下のエラーが発生した。

Tello: 11:08:43.642: Error: video recv: 'TelloNode' object has no attribute 'caminfo'
Traceback (most recent call last):
  File "/home/asakayusuke/catkin_ws/src/tello_driver_for_noetic/src/TelloPy/tellopy/_internal/tello.py", line 808, in __video_thread
    self.__publish(event=self.EVENT_VIDEO_DATA, data=data)
  File "/home/asakayusuke/catkin_ws/src/tello_driver_for_noetic/src/TelloPy/tellopy/_internal/tello.py", line 161, in __publish
    dispatcher.send(event, sender=self, **args)
  File "/home/asakayusuke/catkin_ws/src/tello_driver_for_noetic/src/TelloPy/tellopy/_internal/dispatcher.py", line 35, in send
    receiver(event=sig, **named)
  File "/home/asakayusuke/catkin_ws/src/tello_driver_for_noetic/nodes/tello_driver_node", line 278, in cb_video_data
    self._Tello__publish(event=self.EVENT_VIDEO_FRAME_H264,
  File "/home/asakayusuke/catkin_ws/src/tello_driver_for_noetic/src/TelloPy/tellopy/_internal/tello.py", line 161, in __publish
    dispatcher.send(event, sender=self, **args)
  File "/home/asakayusuke/catkin_ws/src/tello_driver_for_noetic/src/TelloPy/tellopy/_internal/dispatcher.py", line 35, in send
    receiver(event=sig, **named)
  File "/home/asakayusuke/catkin_ws/src/tello_driver_for_noetic/nodes/tello_driver_node", line 466, in cb_h264_frame
    pkt_msg.header.frame_id = self.caminfo.header.frame_id
AttributeError: 'TelloNode' object has no attribute 'caminfo'

camera view以外は正常ですが問題が起きたという意味では上げて損は無いと思ったので共有します。

**Comment by GAI-313** [comment]
それはかなり前に解決したと思うのでクローズしますね。
